name:                postgres-woobat
version:             0.1.0.0
github:              "ollef/postgres-woobat"
license:             BSD3
author:              "Olle Fredriksson"
maintainer:          "fredriksson.olle@gmail.com"
copyright:           "2020 Olle Fredriksson"

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wtabs
  - -funbox-strict-fields

extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- aeson
- barbies
- bytestring
- bytestring-strict-builder
- containers
- generic-lens
- higgledy >= 0.3.0
- lens
- mtl
- postgresql-binary
- postgresql-libpq >= 0.9.4
- scientific
- text
- time
- unordered-containers
- uuid-types

library:
  source-dirs: src

tests:
  postgres-woobat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - postgres-woobat
